services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE=production
    ports:
      - "3000:3000"
    restart: always

  caddy:
    image: caddy:latest
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config: