version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MODE=development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  caddy:
    image: caddy:latest
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config: